### ISSUE TITLE
Update contribution guidelines 

### ISSUE THREAD

**Issue by dkhamsing** [iOS-Goodies/iOS-Goodies#711] opened 2017-03-08 14:06 UTC
Let's discuss when or if it's ok to submit a library / project / article multiple times and update the contribution guidelines 

From #707

**Comment by dkhamsing** [comment] 2017-03-08 14:08
cc @mariusc @tiagoalmeida @RuiAAPeres @rbarbosa

**Comment by tiagoalmeida** [comment] 2017-03-08 14:13
I believe that as a norm it shouldn't be ok. If we open that door on the guidelines people can (and will) retry every time. We can, however, allow for a reevaluation in specific conditions:

- If the week before had a lot of tools (7+, for instance). 
- The request to re-insert should be justified
- We should close the issue anyway (so we don't have repetition in github issues). If we decide to re-insert the tool then we will only do it at the time the issue is posted.

**Closed** 2017-03-12 17:52 UTC
